FROM python:3.11-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

WORKDIR /app

COPY requirements.txt .
RUN uv pip install --system --no-cache -r requirements.txt

COPY app/ ./app/
COPY flask_app/ ./flask_app/
COPY config/ ./config/

CMD ["python", "-m", "flask", "--app", "flask_app/app.py", "run", "--host=0.0.0.0", "--port=5000"]
